---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      "@babel":
        patterns:
          - "@babel*"
      "@eslint":
        patterns:
          - "eslint"
          - "@eslint/js"
      "@tailwindcss":
        patterns:
          - "tailwindcss"
          - "@tailwindcss/vite"
