---
name: Test

on: # yamllint disable-line
  pull_request:

jobs:
  test:
    name: Test Compilation
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm & install packages
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Run tests (build is okay)
        run: pnpm run build:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for astro issues
        run: pnpm run astro:check

      - name: Check for biome issues
        run: pnpm run biome:ci
