---
name: Test

on: # yamllint disable-line
  pull_request:

jobs:
  test:
    name: Test Compilation
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm & install packages
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          version: latest
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: pnpm

      - name: Fetch data
        run: pnpm run fetch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests (build is okay)
        run: pnpm run build

      - name: Check Prettier
        run: pnpm run prettier

      - name: Check ESLint
        run: pnpm run eslint-ci
