---
name: Test

on: # yamllint disable-line
  pull_request:

jobs:
  test:
    name: Test Compilation
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm, Node.js and dependencies
        uses: pnpm/action-setup@v3.1.0
        with:
          cache: true
          require-lockfile: true

      - name: Run tests (build is okay)
        run: pnpm run build:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for astro issues
        run: pnpm run astro:check

      - name: Check for biome issues
        run: pnpm run biome:ci
